### ISSUE TITLE
Duck TODO

### ISSUE THREAD

**Issue by Paspartout** [Paspartout/UntitledDuckMod#1]
- [x] Duck Variant Textures
- [x] Scale ducklings and apply duckling texture and remove wings
- [x] Duck Eggs like chicken eggs?
- [x] Ducks drop duck meat?
- [x] Add spawning similar to chickens?
- [x] Sounds
- [x] Better swimming behaviour
  - [x] Faster swimming on both fabric and forge
- [X] Flapping like chickens
- [ ] Foxes and wolves eat them
  - [ ] Find a way to make that on forge and fabric and not crash(I tried mixins, but they crash randomly on forge)

## Ideas
- Duckling AI; make them follow one of the parents in a single file-line
  - Probably not worth it since there is breeding cooldown?
- Make them tame-able (what would they be used for)?
  - You can sit them down like parrots, but probably not put them on your shoulders(maybe on head?). Maybe ducklings on shoulders :)
- Maybe when they dive there is a chance the come up with seeds in there beak (They then will eat them, but if you kill them before they eat it you can also get some seeds)?
  - The eating should not trigger breeding though. Would make duck farms trivial.

**Comment by pwigary** [comment]
Hello, it is a neat mod, nicely animated, but the duck's beak seems a bit odd,, I think they shouldn't extent all the way with their head, and maybe smaller. <3
